# syntax=docker/dockerfile:1
FROM python:3.11-slim

# install mysqlclient requirements
RUN \
	--mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
	apt-get update && \
	apt-get install -y default-libmysqlclient-dev build-essential

# upgrade pip
RUN pip install --upgrade pip

RUN mkdir /app
WORKDIR /app

# set-up venv
ENV VIRTUAL_ENV=/app/.venv
RUN python -m venv --upgrade-deps $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# install dependencies
COPY requirements.txt .
RUN \
	--mount=type=cache,target=/root/.cache/pip \
	pip install -r requirements.txt

# copy remaining files
COPY main.py .
COPY website website/

EXPOSE 5004
CMD [ "flask", "--app", "main", "run", "--host=0.0.0.0", "--port=5004", "--debug" ]
