import random
from typing import Callable

from flask import Flask, Request, Response

random = random

class SeaSurf:
    def __init__(self, app: Flask | None = None) -> None: ...
    def init_app(self, app: Flask): ...
    def exempt(self, view): ...
    def exempt_urls(self, urls) -> None: ...
    def include(self, view): ...
    def disable_cookie(self, callback: Callable[[Response], bool]): ...
    def set_cookie(self, view): ...
    def skip_validation(self, callback: Callable[[Request], bool]): ...
    def validate(self) -> None: ...
    def generate_new_token(self) -> None: ...
