import random
from typing import Callable, Self, TypeVar

from flask import Flask, Request, Response
from flask.typing import RouteCallable

random = random

T_route = TypeVar("T_route", bound=RouteCallable)

class SeaSurf:
    def __init__(self, app: Flask | None = None) -> None: ...
    def init_app(self, app: Flask) -> Self: ...
    def exempt(self, view: T_route) -> T_route: ...
    def exempt_urls(self, urls: str | tuple[str, ...]) -> None: ...
    def include(self, view: T_route) -> T_route: ...
    def disable_cookie(
        self, callback: Callable[[Response], bool]
    ) -> Callable[[Response], bool]: ...
    def set_cookie(self, view: T_route) -> T_route: ...
    def skip_validation(
        self, callback: Callable[[Request], bool]
    ) -> Callable[[Response], bool]: ...
    def validate(self) -> None: ...
    def generate_new_token(self) -> None: ...
