"""Initial migration

Revision ID: 6139f6e9a81a
Revises: 
Create Date: 2023-06-28 23:22:01.512576

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6139f6e9a81a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=163), nullable=True),
        sa.Column("username", sa.String(length=20), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("image", sa.String(length=100), nullable=True),
        sa.Column("name_github", sa.String(length=100), nullable=True),
        sa.Column("name_youtube", sa.String(length=100), nullable=True),
        sa.Column("name_instagram", sa.String(length=100), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "part",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("image", sa.String(length=100), nullable=True),
        sa.Column("category", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("rejected", sa.Boolean(), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=True),
        sa.Column("tags", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    op.drop_table("part")
    op.drop_table("user")
    # ### end Alembic commands ###
