categories_list = [
    ("Plates", None),
    ("Circular", 1),
    ("Oval", 1),
    ("Special", 1),
    ("Weird", 1),
    ("Holders", None),
    ("Motors", 6),
    ("Sensors", 6),
    ("Microcontrollers and SBCs", 6),
    ("Cameras", 6),
    ("Batteries", 6),
    ("Other", 6),
    ("Special", 6),
    ("Wheels", None),
    ("Smooth", 14),
    ("Normal", 14),
    ("Terrain", 14),
    ("Spikes", 14),
    ("Special", 14),
    ("Connection rods", None),
    ("One hole", 20),
    ("Multi holes", 20),
    ("Special", 20),
]
