name: FA icon list

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  icons-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Check if used FA icons are included
        run: python tests/check_icons.py
